using CodeBase;

/*
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	    P4,n=n^2 	        1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
*/

namespace cs_euler
{
    public class Problem_061 : IProblem
    {
        private static readonly long[] s = new long[6];
        private static readonly long[][] n = new long[6][];

        public long Run()
        {
            int i;
            for (i = 0; i < 6; i++) n[i] = new long[141];
            for (i = 0; i < 122; i++)
            {
                n[0][i] = TriangleNumber.Get(i + 19);
                n[1][i] = SquareNumber.Get(i + 19);
                n[2][i] = PentagonalNumber.Get(i + 19);
                n[3][i] = HexagonalNumber.Get(i + 19);
                n[4][i] = HeptagonalNumber.Get(i + 19);
                n[5][i] = OctagonalNumber.Get(i + 19);
            }
            for (i = 0; i < n[5].Length; i++)
            {
                s[5] = n[5][2];
                FindNext(5, 1);
            }
            return s[0] + s[1] + s[2] + s[3] + s[4] + s[5];
        }

        public static bool FindNext(int a, int b)
        {
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] < 1000)
                {
                    for (int j = 0; j < n[i].Length; j++)
                    {
                        bool u = true;
                        foreach (long l in s)
                        {
                            if (n[i][j] == l)
                            {
                                u = false;
                                break;
                            }
                        }
                        if (u && ((n[i][j] / 100) == (s[a] % 100)))
                        {
                            s[i] = n[i][j];
                            if (b == 5 && s[5] / 100 == s[i] % 100) return true;
                            if (FindNext(i, b + 1)) return true;
                        }
                    }
                    s[i] = 0;
                }
            }
            return false;
        }
    }
}
