using System.Collections.Generic;
using CodeBase;

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/

namespace cs_euler
{
    public class Problem_045 : IProblem
    {
        public long Run()
        {
            HashSet<long> p = new HashSet<long>(), h = new HashSet<long>();
            for (long n = 1; ; n++)
            {
                long c = TriangleNumber.Get(285 + n);
                p.Add(PentagonalNumber.Get(165 + n));
                h.Add(HexagonalNumber.Get(143 + n));
                if (p.Contains(c) && h.Contains(c)) return c;
            }
        }
    }
}
